#!/usr/bin/env python

from __future__ import print_function

import sys

from kattui.base_cmd import KatCam
from kattui.plugin import load_plugins, load_node_conf


if __name__ == '__main__':
    node_conf = load_node_conf()
    app = load_plugins(KatCam, node_conf)

    if len(sys.argv) > 1:
        app.onecmd(' '.join(sys.argv[1:]))
    else:
        app.cmdloop()
